# Generated by Django 4.2.5 on 2023-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caption',
            old_name='url',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='caption',
            name='object_key',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
