apiVersion: apps/v1
kind: Deployment
metadata:
  name: meet-brief-api-deployment
  labels:
    app: meet-brief-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meet-brief-api-deployment
  template:
    metadata:
      labels:
        app: meet-brief-api-deployment
    spec:
      containers:
      - name: meet-brief-api
        image: registry.digitalocean.com/meet-brief/meet-brief-api:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: meet-brief-api-prod-env
        env:
          - name: PORT
            value: "8003"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: meet-brief

---

apiVersion: v1
kind: Service
metadata:
  name: meet-brief-service
spec:
  type: LoadBalancer
  selector:
    app: meet-brief-api-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8003

